### ISSUE TITLE
build with android studio 2.2

### ISSUE THREAD

**Issue by thedreamwork** [wireapp/wire-android#93]
When I download the latest version and try to build with android studio 2.2, it give me below Error :
`wire-core/src/main/java/com/waz/zclient/core/api/scala/ScalaPickUserStore.java:22: error: cannot find symbol
import com.waz.api.ConversationSearchResult;
                  ^
  symbol:   class ConversationSearchResult
  location: package com.waz.api
....`

how can I build?

**Comment by thedreamwork** [comment]
\* What went wrong:
Execution failed for task ':wire-core:compileReleaseJavaWithJavac'.
\> Compilation failed; see the compiler error output for details.

**Comment by someoneEsle** [comment]
I have the same problem. I get over 100 errors.

**Comment by someoneEsle** [comment]
Surprisingly, `./gradlew assembleInternalRelease` works, and actually goes as far as building the apk. However the apk doesn't install, as my phone says "the package seems to be corrupt".

**Comment by cyVR** [comment]
Same here, both errors with graddle and wire-core:compileReleaseJavaWithJavac

**Comment by someoneEsle** [comment]
Can we please get some help? Why is there no answer from anyone in the Wire team yet?

**Comment by zbsz** [comment]
For best results I suggest to use release branch, (latest one is https://github.com/wireapp/wire-android/tree/rel/2.15.x). 
And make sure to select production variant in android studio. 
Building production variant from master branch may often not work, due to library incompatibilities (sometimes there is no matching release sync engine library), we only build dev variants on master.
But dev versions are configured to use internal testing backend, so you won't be able to use that app.

**Comment by someoneEsle** [comment]
When I try to install the apk I build, my phone says impossible to install because the apk is corrupted.
Android 7 Nexus 5X

**Comment by hakonbo** [comment]
Hi all,

please have a look at my answer in https://github.com/wireapp/wire-android/issues/177 and see if you can get the app to build from command line.

**Comment by NetPr** [comment]
Hello,
This issue able close now. No known build errors or major app issues regardless reported bugs on repository.
Follow instruction here https://github.com/wireapp/wire-android/issues/1892 due a certain avs issue fixed few days ago.

**Comment by marcoconti83** [comment]
This is indeed a very old ticket, and plenty of things changed in the 3 years since then. Since there is no feedback from the OP, I'll close. Feel free to reopen if you still have issues.
